### ISSUE TITLE
PostgreSQL migration script?

### ISSUE THREAD

**Issue by nhtones** [DependencyTrack/v3.8.0-v4.0.0-migration#2]
Hi @stevespringett,
Are there any plans to provide a PostgreSQL migration script to update v3.8.0 schemas to support the new v4.0.0 data model?  There doesn't seem to be any mention of PostrgreSQL support being removed  in the upgrade change log https://docs.dependencytrack.org/changelog/.

Many thanks

**Comment by Lake-end** [comment]
Hello, can I ask for timetable on Postgres migration script so we can plan the upgrade to 4.0 better? Thanks!

**Comment by stevespringett** [comment]
@Lake-end to date, nobody has stepped forward to provide Postgres migration scripts. Two people from the community are really close to having a MySQL script available. The logic from that script should provide a Postgres DBA enough information to craft a migration script. As noted in the readme of this project, this is a community effort.

**Comment by Szasza** [comment]
@stevespringett I am happy to pick up the PostgreSQL version, will get to it on Thursday.

**Comment by wargamez** [comment]
Any progress on the Postgres migration script/schema?

**Comment by raddadisaid** [comment]
Any progress on the Postgres migration script/schema? Thank you in advance

**Comment by aksagrimada** [comment]
I am working on a PostgresSQL version as we're keen to get up to 4.x releases for the upcoming Composer support. I am just working through the procedures. 
Did you make any progress @Szasza ?

**Comment by Szasza** [comment]
@aksagrimada thank you for picking it up. I haven't made any progress yet, life happened in the meantime.

**Comment by noqqe** [comment]
Just tried to upgrade to 4.0 using docker  and after some googling found this issue.

Would be really nice if someone could write that migration script for postgres :)

**Comment by aksagrimada** [comment]
I have a 90% complete script. Just resolving some issues with duplicating the component tables in the procedures.

**Comment by aksagrimada** [comment]
Initial version complete. Still some issues around constraints I want to iron out before creating the pull request.
https://github.com/aksagrimada/v3.8.0-v4.0.0-migration/blob/postgres-migration/3.8.0_to_4.0.0_postgres.sql

**Comment by aksagrimada** [comment]
I noticed an issue whilst working on this that may also affect the mysql script. We started at 3.8 so we do not have the SCANS_COMPONENTS table. I added logic to detect if this exists or not in the 3 places it is referenced, not sure if this should just be a case of drop it if it exists.
